const fs = require('fs');
const https = require('https');

const url = 'https://fonts.gstatic.com/s/notosansgeorgian/v48/PlIaFke5O6RzLfvNNVSitxkr76PRHBC4Ytyq-Gof7PUs4S7zWn-8YDB09HFNdpvnzFj-.ttf';
const targetFile = 'c:/Users/jabam/Desktop/BUSINESS/lib/pdf/fonts.ts';

https.get(url, (res) => {
    const chunks = [];
    res.on('data', (chunk) => chunks.push(chunk));
    res.on('end', () => {
        const buffer = Buffer.concat(chunks);
        const base64 = buffer.toString('base64');
        const content = `/**
 * Noto Sans Georgian - Unicode font for PDF generation
 * This file is automatically generated.
 */
export const NOTO_SANS_GEORGIAN_BASE64 = "${base64}";
`;
        fs.writeFileSync(targetFile, content);
        console.log('Font updated successfully!');
    });
}).on('error', (err) => {
    console.error('Error fetching font:', err);
});
